# Site settings
author: Steven Contreras
title: My Adventures in Data Science
header-img: img/home-bg.png
email: steve.a.contreras@gmail.com
copyright_name: Steven Contreras
description: > # this means to ignore newlines until "baseurl:"
  The Journey Begins
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sacontreras

# Build settings
markdown: kramdown
   math_engine: katex
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
